services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: vector-kb
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:8317:8317"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - vector_kb_out:/app/data/out
      - vector_kb_directory:/app/app/services/directory_service/data
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8317

volumes:
  vector_kb_out:
  vector_kb_directory:
